# Site settings
encoding: utf-8
lang: de
title: "Ballettschule Irene Pedrotti"
tagline: "Ballettunterricht für Kinder"
description: |
  Die Ballettschule von Irene Pedrotti in Basel bietet Ballettunterricht
  für Kinder in allen Altersstufen an.
url: "https://www.ballettschule-irenepedrotti.ch"
baseurl: ""
repo: "https://github.com/irenepedrotti/irenepedrotti.github.io"
email: "irene.pedrotti@icloud.com"
css_inline: true
slideshow_images:
  - "/assets/banner2.png"
  - "/assets/banner2.png"
  - "/assets/banner2.png"
  - "/assets/banner2.png"
feature_image: "/assets/banner2.png"
feature_text: "Ballettschule Irene Pedrotti"

# Jekyll settings
markdown: kramdown
sass:
  style: compressed
permalink: pretty
excerpt_separator: <!-- more -->
timezone: Europe/Zurich

# Files excluded from Jekyll builds
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .gitignore
  - .jekyll-cache
  - CNAME
  - LICENSE
  - Readme.md
  - nix
  - shell.nix

# Installed Gems
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jemoji
