# Site settings
encoding: utf-8
lang: de
title: "Ballettschule Irene Pedrotti"
tagline: "Ballettunterricht für Kinder"
url: "https://www.ballettschule-irenepedrotti.ch"
baseurl: ""
repo: "https://github.com/irenepedrotti/irenepedrotti.github.io"
email: "irene.pedrotti@icloud.com"
phone: "+41613025111"
phone_human: "061 302 51 11"
instagram: "ballettschule_pedrotti"
css_inline: true
slideshow_images:
  - "/assets/slideshow/slideshow1.jpg"
  - "/assets/slideshow/slideshow2.jpg"
  - "/assets/slideshow/slideshow3.jpg"
  - "/assets/slideshow/slideshow4.jpg"
gallery_images:
  - "/assets/gallery/DSF5640.jpg"
  - "/assets/gallery/DSF5879.jpg"
  - "/assets/gallery/DSF6172.jpg"
  - "/assets/gallery/R7B7933.jpg"
  - "/assets/gallery/R7B8041.jpg"
  - "/assets/gallery/R7B8304.jpg"
  - "/assets/gallery/R7B8334.jpg"
  - "/assets/gallery/R7B8467.jpg"
  - "/assets/gallery/DSF5706.jpg"
  - "/assets/gallery/DSF6094.jpg"
  - "/assets/gallery/DSF6195.jpg"
  - "/assets/gallery/R7B7984.jpg"
  - "/assets/gallery/R7B8238.jpg"
  - "/assets/gallery/R7B8322.jpg"
  - "/assets/gallery/R7B8364.jpg"
  - "/assets/gallery/R7B8479.jpg"
  - "/assets/gallery/R7B8518.jpg"
  - "/assets/gallery/R7B8522.jpg"
  - "/assets/gallery/R7B7879.jpg"
  - "/assets/gallery/R7B7880.jpg"
  - "/assets/gallery/R7B8491.jpg"

# Extra info for jekyll-seo-tag
social:
  links:
    - https://www.instagram.com/ballettschule_pedrotti

# Jekyll settings
markdown: kramdown
sass:
  style: compressed
permalink: pretty
excerpt_separator: <!-- more -->
timezone: Europe/Zurich

# Compression via <https://github.com/penibelst/jekyll-compress-html>
compress_html:
  comments: all

# Files excluded from Jekyll builds
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .gitignore
  - .jekyll-cache
  - CNAME
  - LICENSE
  - Readme.md
  - nix
  - shell.nix

# Installed Gems
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jemoji
