# Site settings
encoding: utf-8
lang: de
title: "Irene Pedrotti Ballett"
description: "Ballettschule im Studio Movimento" # Site description and default description, also used in jekyll-seo-tag
url: "" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/user/repo"
email: "email@example.com"
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference
feature_image: "/assets/banner2.png"
# feature_text: ""
feature_text: "Ballettschule Irene Pedrotti"


# Jekyll settings
markdown: kramdown
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Zurich # Timezone for blog posts and alike

# Files excluded from Jekyll builds
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .gitignore
  - .jekyll-cache
  - CNAME
  - LICENSE
  - Readme.md

# Installed Gems
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jemoji
